config/routes.rb
Cpnjysep::Application.routes.draw do
  devise_for :users
  resources :articles

  get "ig/auth", as: :ig_auth
  get "ig/callback", as: :ig_callback
  resources :activities
  get "home/about", as: :about
  root "home#index"
  
  get "/auth/:provider/callback", to: "sessions#create"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "JYSEP" %></title>
  <%= csrf_meta_tags %>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
</head>
  <body>
    <nav id="topnav">
      <div class="container">
        <div class="navbar-header">
          <a href="/" class="navbar-brand">Castle Pines North JYSEP</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <%= nav_link "Articles", articles_path %>
            <%= nav_link "Activities", activities_path %>
            <%= nav_link "What is JYSEP?", about_path, true %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
            <% if user_signed_in? %>
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes"><strong><%= current_user.email %>  <span class="caret"></span></strong></a>
              <ul class="dropdown-menu" aria-labelledby="themes">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            <% else %>
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Sign In <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="themes">
                <li><%= link_to (fa_icon("twitter").html_safe + " Twitter"), "/auth/twitter" %></li>
                <li><%= link_to (fa_icon("twitter").html_safe + " Twitter"), "/auth/twitter" %></li>
              </ul>
            <% end %>
          </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
      <hr />
      <footer>
        <div class="row">
          <div class="col-lg-12">
            <p class="pull-right"><a href="#">Back to top</a></p>
            &copy; 2013 Castle Pines Junior Youth Spiritual Empowerment Program
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>